### ISSUE TITLE
utils.lisp location

### ISSUE THREAD

**Issue by parjanya** [hellerve/sbcli#21]
At least here `(load "utils.lisp")` makes invoking sbcli only work inside its own directory; where should it go instead? to `/usr/local/bin/` too? or just put its content inside `repl.lisp`?

**Comment by hellerve** [comment]
Ah yes, that’s a problem of course. I’d say we keep the file self-contained and inline the contents of `utils.lisp`. What do you think @vindarel?

**Comment by vindarel** [comment]
ooh, right. OK, let's keep the file self-contained.

**Comment by hellerve** [comment]
I just pushed a commit inlining `utils.lisp`. That should resolve this.
