### ISSUE TITLE
pygmentize has problems

### ISSUE THREAD

**Issue by max-bertinetti** [hellerve/sbcli#23]
Hi @hellerve.

I'm trying to use pygmentize.

It output the help on the prompt and don't let use the CLI:

❯ sbcli        
My LISP REPL version 0.1.3
Press CTRL-D or type :q to exit

`> Usage: /home/max/.local/bin/pygmentize [-l <lexer> | -g] [-F <filter>[:<options>]] [-f <formatter>]`

I'm on Linux with Python 3.8 and last Pygments version

**Comment by vindarel** [comment]
Hello,

The command line that sbcli tries to run is:

    /path/to/pygmentize -s -l lisp <input string>

I suppose this doesn't produce a coloured output for you? Can you find one command that works?

Plus I wonder what's the best to check that the command succeeded. 

It's working for me on Python 2.7. You can set the path to a pygments version with the `*pygmentize*` variable.

**Comment by max-bertinetti** [comment]
I set the path in the configuration.

Python 2 is not an option. Any modern Linux distribution doesn't have it anymore..

**Comment by hellerve** [comment]
Hey, thanks for the report! I cannot reproduce this issue on MacOS with Python 3.9.10 and Pygments 2.11.2.

Since my help output also looks different, I have to ask what `pygmentize -V` prints for you?

**Comment by max-bertinetti** [comment]
Found the problem: On my system there was an old version also and is the one present in $HOME/.local/bin.
Removed the old and reinstalled the last now it works!
Thanks

**Comment by hellerve** [comment]
Thanks for letting us know!
